---
- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=600

- name: Install Docker engine prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present


- name: Add Docker's official GPG key
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

# Output of lsb_release might be like 'buster', 'stretch' and 'jessie'      
- name: Get distribution name
  command: >
    lsb_release -cs
  register: lsb_release  
  
- name: Add Docker apt repository.
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ lsb_release.stdout }} stable"
    state: present
    update_cache: true

- name: Install Docker
  apt:
    name:
      - docker-ce=5:19.03.10~3-0~debian-{{ lsb_release.stdout  }} 
      - containerd.io
    state: present
  # notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true 

- name: Install docker-compose
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.29.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
    